/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mmm;

/**
 *
 * @author naimyoussiftraore
 */
public enum mmmLanguageProperty {

    LIST_STATIONS_ICON,
    PLUS_ICON,
    MINUS_ICON,
    ROTATE_ICON,
    ROUTE_ICON,
    ZOOM_IN_ICON,
    ZOOM_OUT_ICON,
    BOLD_ICON,
    ITALIC_ICON,
    ADD_LINE_TOOLTIP,
    REMOVE_LINE_TOOLTIP,
    EDIT_LINE_NAME_TOOLTIP,
    EDIT_LINE_COLOR_TOOLTIP,
    ADD_STATION_TO_LINE_TOOLTIP,
    REMOVE_STATION_FROM_LINE_TOOLTIP,
    LIST_ALL_STATIONS_TOOLTIP,
    CHANGE_LINE_THICKNESS_TOOLTIP,
    ADD_STATION_TOOLTIP,
    REMOVE_STATION_TOOLTIP,
    SNAP_TO_GRID_TOOLTIP,
    MOVE_STATION_LABEL_TOOLTIP,
    ROTATE_STATION_LABEL_TOOLTIP,
    CHANGE_STATION_COLOR_TOOLTIP,
    CHANGE_STATION_RADIUS_TOOLTIP,
    START_STATION_TOOLTIP,
    END_STATION_TOOLTIP,
    FIND_ROUTE_TOOLTIP,
    CHANGE_BACKGROUND_COLOR_TOOLTIP,
    SET_BACKGROUND_IMAGE_TOOLTIP,
    ADD_IMAGE_TOOLTIP,
    ADD_LABEL_TOOLTIP,
    REMOVE_ELEMENT_TOOLTIP,
    CHANGE_TEXT_COLOR_TOOLTIP,
    FONT_FAMILY_TOOLTIP,
    FONT_SIZE_TOOLTIP,
    BOLD_TOOLTIP,
    ITALIC_TOOLTIP,
    ZOOM_IN_TOOLTIP,
    ZOOM_OUT_TOOLTIP,
    METRO_LINES_LABEL,
    METRO_STATIONS_LABEL,
    DECOR_LABEL,
    FONT_LABEL,
    NAVIGATION_LABEL,
    EDIT_STATION_NAME_TOOLTIP,
    COLLAPSE_ICON,
    EXPAND_ICON,
    COLLAPSE_TOOLTIP,
    EXPAND_TOOLTIP;

}
